spring:
  application:
    name: eureka-provider-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      ## defaultZone: http://localhost:8762/eureka/,http://127.0.0.1:8761/eureka/


server:
  port: 8001

name: 8001-test