server:
  port: 8761 #服务注册中心端口号
eureka:
  instance:
    hostname: eureka1
  server:
    enable-self-preservation: false #关闭自我保护机制
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心位置
      defaultZone: http://127.0.0.1:8762/eureka/